paths:
  data: '/Users/rolando/Development/athlete-identification-and-personel-pro-file-creation-based-on-movement-sensor-data/data/processed/diodora/single_stride/lumbar/data.npy'
  labels: '/Users/rolando/Development/athlete-identification-and-personel-pro-file-creation-based-on-movement-sensor-data/data/processed/diodora/single_stride/lumbar/labels.csv'