paths:
#  data: '/Users/rolando/Development/athlete-identification-and-personel-pro-file-creation-based-on-movement-sensor-data/data/processed/diodora/single_stride/lumbar/data.npy'
#  labels: '/Users/rolando/Development/athlete-identification-and-personel-pro-file-creation-based-on-movement-sensor-data/data/processed/diodora/single_stride/lumbar/labels.csv'
  data: '/Users/rolando/Development/athlete-identification-and-personel-pro-file-creation-based-on-movement-sensor-data/data/processed/diodora/all_strides/lumbar'
  labels: '/Users/rolando/Development/athlete-identification-and-personel-pro-file-creation-based-on-movement-sensor-data/data/processed/diodora/all_strides/lumbar/labels.csv'

dimensions: [x, y, z]